### ISSUE TITLE
killMails.js has incorrect casing in npm version

### ISSUE THREAD

**Issue by GeekyAubergine** [GingkathFox/esiJS#12]
In [endpoints.js](https://github.com/GingkathFox/esiJS/blob/master/endpoints.js), [killMails.js](https://github.com/GingkathFox/esiJS/blob/master/Functions/killMails.js) is imported as `killmails: require('./Functions/killMails'),`. The version available on npm has the file kill mails cased as `killmails.js` resulting in not node/webpack being able to import the file. The file is correctly typed within the source code though which leads me to believe it is related to the build system used. As such I don't think I am able to fix this with a pr, what build system are you using?

**Comment by 0xf0xx0** [comment]
aah, i see. Yeah, my macOS isnt case-sensitive, thats probably why. Fixing now
