### ISSUE TITLE
Bug in README example?

### ISSUE THREAD

**Issue by ErikKalkoken** [GingkathFox/esiJS#19]
I was trying out your library and I think I found a bug in the example.

The following resulted in "MODULE NOT FOUND".

```javascript
const esiJS = require('esiJS')
```

Had to change it to:

```javascript
const esiJS = require('esijs')
```

My platform is Ubuntu btw.

If you agree I can make a PR.

**Comment by 0xf0xx0** [comment]
Oop, thanks for pointing that out! Ill fix that, dunno why i did it in the first place
