### ISSUE TITLE
README example instantiation doesn't work

### ISSUE THREAD

**Issue by Eingang** [GingkathFox/esiJS#20]
In the READMe.md file, your sample code uses a zero-argument constructor for the esiJS class:

```js
const esiJS = require('esijs')
const esiClient = new esiJS()
```

This generates a `TypeError: Cannot read property 'logging' of undefined` because you need to instantiate using something like:

```js
const esiJS = require('esijs')
const esiClient = new esiJS({logging: false})
```
The sample code in the ['How To Install esiJS' wiki page](https://github.com/GingkathFox/esiJS/wiki/How-to-install-esiJS) is also wrong (and still has `require('esiJS')` too).

**Comment by 0xf0xx0** [comment]
goddammit, lemmie fix that, thanks for reporting!
