### ISSUE TITLE
[BUG] Corporation Alliance History is setup wrong

### ISSUE THREAD

**Issue by Tmktahu** [GingkathFox/esiJS#26]
The `corporation` group has an entry for `corporationHistory` that seems to be set up wrong.
https://github.com/ExperiBass/esiJS/blob/1465a2807cb6316b4bbcfe841cc72891ea721a23/src/corporation.js#L4-L19

The comment seems to acknowledge that this is meant to be for the corporation's alliance history, but it is named wrong and attempts to send a request to a `corporations/${corporationID}/corporationhistory` endpoint which doesn't exist.

I believe this may be a copy-paste error and needs to be updated to point at the `/corporations/${corporationID}/alliancehistory/` ESI route instead.

**Comment by 0xf0xx0** [comment]
ah youre right, good catch uwu

**Comment by 0xf0xx0** [comment]
alright, published on npm uwu
